# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
	def setupUi(self, mainWindow):
		mainWindow.setObjectName("mainWindow")
		mainWindow.resize(640, 510)
		mainWindow.setMouseTracking(True)
		mainWindow.setToolTip("")
		mainWindow.setDocumentMode(False)
		self.centralwidget = QtWidgets.QWidget(mainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.tabTank = QtWidgets.QTabWidget(self.centralwidget)
		self.tabTank.setGeometry(QtCore.QRect(0, 0, 651, 461))
		self.tabTank.setMovable(True)
		self.tabTank.setObjectName("tabTank")
		self.tab1 = QtWidgets.QWidget()
		self.tab1.setObjectName("tab1")
		self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab1)
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 641, 433))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setSpacing(2)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.formLayout = QtWidgets.QFormLayout()
		self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
		self.formLayout.setContentsMargins(5, 12, 5, -1)
		self.formLayout.setVerticalSpacing(11)
		self.formLayout.setObjectName("formLayout")
		self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label.setObjectName("label")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
		self.cPercent = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
		self.cPercent.setProperty("value", 38)
		self.cPercent.setAlignment(QtCore.Qt.AlignCenter)
		self.cPercent.setInvertedAppearance(False)
		self.cPercent.setObjectName("cPercent")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cPercent)
		self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
		self.cCapacity = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.cCapacity.setObjectName("cCapacity")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cCapacity)
		self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_3.setObjectName("label_3")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
		self.cSerial = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.cSerial.setObjectName("cSerial")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cSerial)
		self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_4.setObjectName("label_4")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
		self.cDesign = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.cDesign.setObjectName("cDesign")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cDesign)
		self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_5.setObjectName("label_5")
		self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
		self.cUnite = QtWidgets.QComboBox(self.horizontalLayoutWidget)
		self.cUnite.setObjectName("cUnite")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.cUnite.addItem("")
		self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cUnite)
		self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_6.setObjectName("label_6")
		self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
		self.cType = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.cType.setObjectName("cType")
		self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cType)
		self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_7.setObjectName("label_7")
		self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
		self.cFull = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.cFull.setObjectName("cFull")
		self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cFull)
		self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_8.setObjectName("label_8")
		self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
		self.cHeight = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.cHeight.setObjectName("cHeight")
		self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cHeight)
		self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_9.setObjectName("label_9")
		self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
		self.cTemp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
		self.cTemp.setObjectName("cTemp")
		self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cTemp)
		self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_10.setObjectName("label_10")
		self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
		self.cTime = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
		self.cTime.setInputMethodHints(QtCore.Qt.ImhNone)
		self.cTime.setReadOnly(True)
		self.cTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
		self.cTime.setKeyboardTracking(False)
		self.cTime.setObjectName("cTime")
		self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cTime)
		self.label_51 = QtWidgets.QLabel(self.horizontalLayoutWidget)
		self.label_51.setObjectName("label_51")
		self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_51)
		self.cAction = QtWidgets.QComboBox(self.horizontalLayoutWidget)
		self.cAction.setObjectName("cAction")
		self.cAction.addItem("")
		self.cAction.addItem("")
		self.cAction.addItem("")
		self.cAction.addItem("")
		self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.cAction)
		self.horizontalLayout.addLayout(self.formLayout)
		self.dCiterne = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
		self.dCiterne.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.dCiterne.sizePolicy().hasHeightForWidth())
		self.dCiterne.setSizePolicy(sizePolicy)
		self.dCiterne.setMinimumSize(QtCore.QSize(256, 429))
		self.dCiterne.setBaseSize(QtCore.QSize(256, 429))
		self.dCiterne.setAcceptDrops(False)
		self.dCiterne.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.dCiterne.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.dCiterne.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
		brush.setStyle(QtCore.Qt.NoBrush)
		self.dCiterne.setForegroundBrush(brush)
		self.dCiterne.setSceneRect(QtCore.QRectF(0.0, 0.0, 256.0, 429.0))
		self.dCiterne.setObjectName("dCiterne")
		self.horizontalLayout.addWidget(self.dCiterne)
		self.tabTank.addTab(self.tab1, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setEnabled(False)
		self.tab_2.setObjectName("tab_2")
		self.tabTank.addTab(self.tab_2, "")
		mainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(mainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 24))
		self.menubar.setObjectName("menubar")
		self.menuFichier = QtWidgets.QMenu(self.menubar)
		self.menuFichier.setObjectName("menuFichier")
		self.menuHelp = QtWidgets.QMenu(self.menubar)
		self.menuHelp.setObjectName("menuHelp")
		self.menuLangues = QtWidgets.QMenu(self.menuHelp)
		self.menuLangues.setObjectName("menuLangues")
		mainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(mainWindow)
		self.statusbar.setObjectName("statusbar")
		mainWindow.setStatusBar(self.statusbar)
		self.actionQuitter = QtWidgets.QAction(mainWindow)
		self.actionQuitter.setShortcut("Ctrl+Q")
		self.actionQuitter.setMenuRole(QtWidgets.QAction.QuitRole)
		self.actionQuitter.setObjectName("actionQuitter")
		self.actionApropos = QtWidgets.QAction(mainWindow)
		self.actionApropos.setObjectName("actionApropos")
		self.actionFran_ais = QtWidgets.QAction(mainWindow)
		self.actionFran_ais.setCheckable(True)
		self.actionFran_ais.setChecked(True)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("icons/svg/fra.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionFran_ais.setIcon(icon)
		self.actionFran_ais.setShortcut("")
		self.actionFran_ais.setMenuRole(QtWidgets.QAction.PreferencesRole)
		self.actionFran_ais.setObjectName("actionFran_ais")
		self.actionItalien = QtWidgets.QAction(mainWindow)
		self.actionItalien.setCheckable(True)
		self.actionItalien.setEnabled(False)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("icons/svg/ita.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionItalien.setIcon(icon1)
		self.actionItalien.setMenuRole(QtWidgets.QAction.PreferencesRole)
		self.actionItalien.setObjectName("actionItalien")
		self.actionAllemand = QtWidgets.QAction(mainWindow)
		self.actionAllemand.setCheckable(True)
		self.actionAllemand.setEnabled(True)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("icons/svg/deu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAllemand.setIcon(icon2)
		self.actionAllemand.setMenuRole(QtWidgets.QAction.PreferencesRole)
		self.actionAllemand.setObjectName("actionAllemand")
		self.actionAnglais = QtWidgets.QAction(mainWindow)
		self.actionAnglais.setCheckable(True)
		self.actionAnglais.setEnabled(False)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("icons/svg/gbr.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAnglais.setIcon(icon3)
		self.actionAnglais.setMenuRole(QtWidgets.QAction.PreferencesRole)
		self.actionAnglais.setObjectName("actionAnglais")
		self.actionPr_ferences = QtWidgets.QAction(mainWindow)
		self.actionPr_ferences.setObjectName("actionPr_ferences")
		self.menuFichier.addAction(self.actionQuitter)
		self.menuLangues.addAction(self.actionFran_ais)
		self.menuLangues.addAction(self.actionItalien)
		self.menuLangues.addAction(self.actionAllemand)
		self.menuLangues.addAction(self.actionAnglais)
		self.menuHelp.addAction(self.menuLangues.menuAction())
		self.menuHelp.addAction(self.actionPr_ferences)
		self.menuHelp.addSeparator()
		self.menuHelp.addAction(self.actionApropos)
		self.menubar.addAction(self.menuFichier.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(mainWindow)
		self.tabTank.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(mainWindow)

	def retranslateUi(self, mainWindow):
		_translate = QtCore.QCoreApplication.translate
		mainWindow.setWindowTitle(_translate("mainWindow", "KSW_Gok"))
		self.label.setText(_translate("mainWindow", "Ponrcentage de remplissage:"))
		self.label_2.setText(_translate("mainWindow", "Litrage:"))
		self.label_3.setText(_translate("mainWindow", "Citerne / No de serie:"))
		self.label_4.setText(_translate("mainWindow", "Désignation de la citerne:"))
		self.label_5.setText(_translate("mainWindow", "Unité:"))
		self.cUnite.setCurrentText(_translate("mainWindow", "Litres"))
		self.cUnite.setItemText(0, _translate("mainWindow", "Litres"))
		self.cUnite.setItemText(1, _translate("mainWindow", "Metre Cube"))
		self.cUnite.setItemText(2, _translate("mainWindow", "Pourcent"))
		self.cUnite.setItemText(3, _translate("mainWindow", "Hauteur(m)"))
		self.cUnite.setItemText(4, _translate("mainWindow", "Kilogramme"))
		self.cUnite.setItemText(5, _translate("mainWindow", "IG"))
		self.cUnite.setItemText(6, _translate("mainWindow", "UG"))
		self.cUnite.setItemText(7, _translate("mainWindow", "Tonne"))
		self.cUnite.setItemText(8, _translate("mainWindow", "milliBar"))
		self.cUnite.setItemText(9, _translate("mainWindow", "kiloPascal"))
		self.label_6.setText(_translate("mainWindow", "Type de citerne:"))
		self.label_7.setText(_translate("mainWindow", "Volume de la citerne:"))
		self.label_8.setText(_translate("mainWindow", "Hauteur de la citerne"))
		self.label_9.setText(_translate("mainWindow", "Temperature:"))
		self.label_10.setText(_translate("mainWindow", "Date / Heure de la mesure:"))
		self.cTime.setDisplayFormat(_translate("mainWindow", "dd.MM.yyyy HH:mm"))
		self.label_51.setText(_translate("mainWindow", "Action:"))
		self.cAction.setCurrentText(_translate("mainWindow", "E-Mails..."))
		self.cAction.setItemText(0, _translate("mainWindow", "E-Mails..."))
		self.cAction.setItemText(1, _translate("mainWindow", "SMS..."))
		self.cAction.setItemText(2, _translate("mainWindow", "SMNP...."))
		self.cAction.setItemText(3, _translate("mainWindow", "Graphique..."))
		self.tabTank.setTabText(self.tabTank.indexOf(self.tab1), _translate("mainWindow", "Citerne 1"))
		self.tabTank.setTabText(self.tabTank.indexOf(self.tab_2), _translate("mainWindow", "Tab 2"))
		self.menuFichier.setTitle(_translate("mainWindow", "Fic&hier"))
		self.menuHelp.setTitle(_translate("mainWindow", "Aide"))
		self.menuLangues.setTitle(_translate("mainWindow", "&Langues"))
		self.actionQuitter.setText(_translate("mainWindow", "&Quitter"))
		self.actionApropos.setText(_translate("mainWindow", "&A propos"))
		self.actionFran_ais.setText(_translate("mainWindow", "&Français"))
		self.actionItalien.setText(_translate("mainWindow", "&Italien"))
		self.actionAllemand.setText(_translate("mainWindow", "&Allemand"))
		self.actionAnglais.setText(_translate("mainWindow", "A&nglais"))
		self.actionPr_ferences.setText(_translate("mainWindow", "&Préferences..."))
import gok_rc
