# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(640, 510)
        mainWindow.setMouseTracking(True)
        mainWindow.setToolTip("")
        mainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabTank = QtWidgets.QTabWidget(self.centralwidget)
        self.tabTank.setGeometry(QtCore.QRect(0, 0, 651, 461))
        self.tabTank.setMovable(True)
        self.tabTank.setObjectName("tabTank")
		
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 641, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(5, 12, 5, -1)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cPercent = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.cPercent.setProperty("value", 38)
        self.cPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.cPercent.setInvertedAppearance(False)
        self.cPercent.setObjectName("cPercent")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cPercent)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cCapacity = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cCapacity.setObjectName("cCapacity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cCapacity)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cSerial = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cSerial.setObjectName("cSerial")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cSerial)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cDesign = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cDesign.setObjectName("cDesign")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cDesign)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cUnite = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cUnite.setCurrentText("")
        self.cUnite.setObjectName("cUnite")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cUnite)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cType = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cType.setObjectName("cType")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cType)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cFull = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cFull.setObjectName("cFull")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cFull)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cHeight = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cHeight.setObjectName("cHeight")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cHeight)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cTemp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cTemp.setObjectName("cTemp")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cTemp)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cTime = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
        self.cTime.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cTime.setReadOnly(True)
        self.cTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cTime.setKeyboardTracking(False)
        self.cTime.setObjectName("cTime")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.cTime)
        self.horizontalLayout.addLayout(self.formLayout)
        self.dCiterne = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.dCiterne.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dCiterne.sizePolicy().hasHeightForWidth())
        self.dCiterne.setSizePolicy(sizePolicy)
        self.dCiterne.setMinimumSize(QtCore.QSize(256, 429))
        self.dCiterne.setBaseSize(QtCore.QSize(256, 429))
        self.dCiterne.setAcceptDrops(False)
        self.dCiterne.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dCiterne.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dCiterne.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.dCiterne.setForegroundBrush(brush)
        self.dCiterne.setSceneRect(QtCore.QRectF(0.0, 0.0, 256.0, 429.0))
        self.dCiterne.setObjectName("dCiterne")
        self.horizontalLayout.addWidget(self.dCiterne)
        self.tabTank.addTab(self.tab1, "")
		
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.tabTank.addTab(self.tab_2, "")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 24))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(mainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(mainWindow)
        self.tabTank.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "KSW_Gok"))
        self.label.setText(_translate("mainWindow", "Ponrcentage de remplissage:"))
        self.label_2.setText(_translate("mainWindow", "Litrage:"))
        self.label_3.setText(_translate("mainWindow", "Citerne / No de serie:"))
        self.label_4.setText(_translate("mainWindow", "Désignation de la citerne:"))
        self.label_5.setText(_translate("mainWindow", "Unité:"))
        self.label_6.setText(_translate("mainWindow", "Type de citerne:"))
        self.label_7.setText(_translate("mainWindow", "Volume de la citerne:"))
        self.label_8.setText(_translate("mainWindow", "Hauteur de la citerne"))
        self.label_9.setText(_translate("mainWindow", "Temperature:"))
        self.label_10.setText(_translate("mainWindow", "Date / Heure de la mesure:"))
        self.cTime.setDisplayFormat(_translate("mainWindow", "dd.MM.yyyy HH:mm"))
        self.tabTank.setTabText(self.tabTank.indexOf(self.tab1), _translate("mainWindow", "Citerne 1"))
        self.tabTank.setTabText(self.tabTank.indexOf(self.tab_2), _translate("mainWindow", "Tab 2"))
        self.menuFichier.setTitle(_translate("mainWindow", "Fic&hier"))
        self.actionQuitter.setText(_translate("mainWindow", "&Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
